### ISSUE TITLE
Leaving out spaces

### ISSUE THREAD

**Issue by elliotttate** [tobyxdd/bread#3]
Great job on the script! It works really well most of the time. The two issues I'm running into are 1. Many websites lose a space between some words as in: https://www.pcgamer.com/im-begging-space-sims-to-stop-turning-themselves-into-shooters/

The other is that on longer sites like Reddit comments, the first few comments have it on, but then the rest of the thread doesn't. Thanks again for making this!

**Comment by tobyxdd** [comment]
Thanks for the feedback elliotttate! 1.0.3 should have fixed the problem of missing spaces.

As for your second issue - this script currently only runs when a page is first loaded, so it doesn't apply for dynamically loaded content. I'll try to get it to work in a later update.

**Comment by skygate2012** [comment]
@tobyxdd In modern js you can just use [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) and call processNode on each mutation.
